apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    env: {{ .Values.environment }}
spec:
  replicas: {{ .Values.postgres.podReplicas }}
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag | default "latest" }}"
          imagePullPolicy: "{{ .Values.postgres.image.pullPolicy }}"
          ports:
            - name: {{ .Values.postgres.containerPort.tcp.name }}
              containerPort: {{ .Values.postgres.containerPort.tcp.port }}
              protocol: TCP
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          env:
            {{- range .Values.postgres.env }}
            - name: {{ .name }}
              value: {{ tpl .value $ | quote }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu }}
              memory: {{ .Values.postgres.resources.requests.memory }}
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu }}
              memory: {{ .Values.postgres.resources.limits.memory }}
