apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-sysbench
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sysbench
          image: "{{ .Values.sysbench.image.repository }}:{{ .Values.sysbench.image.tag | default "latest" }}"
          command: ["/bin/bash", "-c"]
          args:
            - |
              sysbench oltp_common --db-driver=pgsql --pgsql-host=postgres-svc --pgsql-user=admin --pgsql-password=$DB_PASS prepare