apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-svc
    env: {{ .Values.environment }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.postgres.containerPort.tcp.name }}
      port: {{ .Values.postgres.containerPort.tcp.port }}
      protocol: TCP
      targetPort: {{ .Values.postgres.containerPort.tcp.port }}
  selector:
    app: postgres
